### ISSUE TITLE
Cromely and React

### ISSUE THREAD

**Issue by cesarecaoduro** [alfarok/DynamoViewport#18]
Love the idea! I was trying to get something very similar to work with Cromely and React. Although I don't get exactly the way you send the tasks to be executed from the front-end!
This is actually a very interesting solution that should be further developed.

**Comment by alfarok** [comment]
Hey @cesarecaoduro, thanks for the positive feedback!  

The strategy for communicating with Dynamo as a 3rd party app or host integration usually depends on a lot of factors.  Many of the host integrators such as Civil3D, Revit, Alias all use slightly different approaches.  Depending on what you want to accomplish a local server and web request or web socket approach may work but you have to also consider that Dynamo sandbox is multi-threaded while Revit runs Dynamo on a single thread so handling async calls can be a pain.  CEFSharp allows you to embed chromium in .NET apps and was what I explored here.  It works but is maintained mainly by a single dev and you can run into issues if multiple tools in the same environment are relying on different versions of CEF but overall it got the job done.  When the render data on a node updates, another property change event is raised which sends the backing geometry data as json to the chrome session. (could be more efficient)

It's good to see projects like Chromely seeking to lighten up electron.  I have messed around with some similar stuff using Vue for my personal website, [alfarok.io/sketches/webgl-basic-material](https://alfarok.io/sketches/webgl-basic-material).  If there is enough interest in the Dynamo integration I would consider spending a little more time here since it was mainly completed in a couple weeks several years ago now during a research sprint.

Let me know if you have any other questions, cheers!

**Comment by cesarecaoduro** [comment]
Great,
My idea is to use the webgl engine to give a more “realistic” look to Dynamo.
Not really interested at the moment for the Revit side but more into the geometrical part of dynamo.
The ability to inject material to object or to use gltf loader to bring custom geometry to substitute Dynamo geometry (e.g.: a point for a tree, mesh for a terrain, etc)
The implications using GIS data can be massive :)

The other portion of the idea is to bring real-time geometry manipulation of simple objects like in Dynashape to move lines and point and see how the geometry responds to that.

I’m happy to work with you if you are interested. This can be a game changer!

Thanks Cesare

Cesare Caoduro
________________________________

**Comment by alfarok** [comment]
@cesarecaoduro I was definitely thinking along similar lines when I started the project.  You can do some fun and interesting things with the render loop and animations as well.  One thing to be cautious about is thinking about how manual manipulations influence the graph state.  For example, after a manual manipulation does a re-execution of the graph cause you to lose the previous manipulation?  There are several ways to handle such an occurrence, just something to be aware of.

I don't think I have the time right now to bring this project to a production level but am always open to collaborating or reviewing pull requests.  If this project receives some public contributions I would be more inclined to continue the development :smiley:
