### ISSUE TITLE
Not allowed to load local resource: 

### ISSUE THREAD

**Issue by LUC-ian** [alfarok/DynamoViewport#22]
hi, 
I keep getting the error listed below when I click on Launch Viewport. Any thoughts on how to get around it? 
Not allowed to load local resource: file:///C:/Users/lucia/AppData/Roaming/Dynamo/Dynamo%20Core/2.8/packages/Viewport/extra/index.html

**Comment by LUC-ian** [comment]
my chrome version is: 
Version 85.0.4183.121 (Official Build) (64-bit)

**Comment by LUC-ian** [comment]
somehow I've got it working, but I have no idea what I've done...my guess is that in dev mode is running on port 8088 which is restricted, but I'm not sure. Basically, what I did was to change the port to 8000 then change it back to 8088.

**Comment by alfarok** [comment]
Hey!  I don't think I have come across this error before on my end.  It definitely looks permissions related but I don't think it's related to the port because Dynamo already uses 8088 to debug the javascript/typscript based library:

![image](https://user-images.githubusercontent.com/13341935/93932624-7c892480-fcee-11ea-8df9-54f132492f5b.png)

One other thought maybe the external debugging window I am launching when built in debug mode:

![image](https://user-images.githubusercontent.com/13341935/93932842-c7a33780-fcee-11ea-8c06-143234ad6600.png)

Let me know if it's still an issue or try building in release to avoid the debugging window.  If not feel free to close this and reopen if you encounter the problem again with any additional info.  I may add this to the package manager in the future if I find the time now that extensions are supported and the extensions panel is available.
